# Generated by Django 3.1.3 on 2021-05-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20210504_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('calc', models.BooleanField(default=False)),
                ('value', models.IntegerField()),
                ('contrib', models.IntegerField()),
                ('pay', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='avail_date',
            new_name='date_req',
        ),
        migrations.RemoveField(
            model_name='service',
            name='req_date',
        ),
        migrations.AddField(
            model_name='apart',
            name='sqr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apart',
            name='nbr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='prof_req',
            field=models.CharField(blank=True, choices=[('e', 'electric'), ('s', 'sanitary'), ('c', 'cleaning')], default='s', help_text='Required service type', max_length=1),
        ),
    ]
