# Generated by Django 3.1.3 on 2021-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20210510_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apart',
            name='id',
        ),
        migrations.AlterField(
            model_name='apart',
            name='nbr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
