# Generated by Django 3.1.3 on 2021-05-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20210512_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrual',
            name='nbr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.apart'),
        ),
    ]
