# Generated by Django 3.1.3 on 2021-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_accrual_nbr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accrual',
            old_name='value',
            new_name='accrued',
        ),
        migrations.RenameField(
            model_name='accrual',
            old_name='pay',
            new_name='confirm',
        ),
        migrations.RemoveField(
            model_name='accrual',
            name='calc',
        ),
        migrations.RemoveField(
            model_name='accrual',
            name='rate',
        ),
        migrations.AddField(
            model_name='accrual',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
